### ISSUE TITLE
When installing the Pulsar Node.js client, the operation steps need to be optimized

### ISSUE THREAD

**Issue by zhaoyajun2009** [apache/pulsar-client-node#188]
**In step “Prerequisites”, in addition to the c++ library, you need to install gcc and g++ dependency, otherwise the following problems will occur in step “Install pulsar-client in your project” later：**

[ec2-user@ip-172-31-0-126 ~]$ npm install pulsar-client
npm ERR! code 1
npm ERR! path /home/ec2-user/node_modules/pulsar-client   
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! make: 进入目录“/home/ec2-user/node_modules/pulsar-client/build”
npm ERR!   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR! make: 离开目录“/home/ec2-user/node_modules/pulsar-client/build”
npm ERR! Failed to execute '/home/ec2-user/node-v16.13.1-linux-x64/bin/node /home/ec2-user/node-v16.13.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ec2-user/node_modules/pulsar-client/build/Release/libpulsar.node --module_name=libpulsar --module_path=/home/ec2-user/node_modules/pulsar-client/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1

**Comment by Hoskins355** [comment]
I am facing the same. @zhaoyajun2009 did you get it working?

**Comment by zhaoyajun2009** [comment]
> you need to install gcc and g++ dependency

you need to install gcc and g++ dependency

**Comment by zhaoyajun2009** [comment]
> I am facing the same. @zhaoyajun2009 did you get it working?
you need to install gcc and g++ dependency with the command of ‘yum install’。

**Comment by Hoskins355** [comment]
I am trying to install with Docker https://gist.github.com/Hoskins355/c36c9d4c1c69e55427d5ec58d44a2009 using base image "apachepulsar/pulsar-build:centos-7" which should have all dependencies. I tried to add gcc and g++ as well but I am still getting the same error.

**Comment by zhaoyajun2009** [comment]
I installed the dependency by install RPM package,(https://pulsar.apache.org/docs/en/client-libraries-cpp/#compilation),
The success result is the file as below is created in /usr/lib ：
lrwxrwxrwx  1 root root       18 12月 30 22:21 libpulsar.so -> libpulsar.so.2.9.1
lrwxrwxrwx  1 root root       23 12月 30 22:21 libpulsarnossl.so -> libpulsarnossl.so.2.9.1

Then I installed the gcc and g++ by yum as below：
sudo yum -y install gcc automake autoconf libtool make
sudo yum -y install gcc-c++

-----
> I am trying to install with Docker https://gist.github.com/Hoskins355/c36c9d4c1c69e55427d5ec58d44a2009 using base image "apachepulsar/pulsar-build:centos-7" which should have all dependencies. I tried to add gcc and g++ as well but I am still getting the same error.

**Comment by Hoskins355** [comment]
I got Libpulsar.so in usr/lib
<img width="283" alt="Screen Shot 2022-01-07 at 10 07 24 AM" src="https://user-images.githubusercontent.com/3084440/148573912-1e9bfce4-68e4-4d7a-9f88-edccd5d7e527.png">
and I copied that directory into the docker container and changed the permission on it. 
<img width="266" alt="Screen Shot 2022-01-07 at 10 08 02 AM" src="https://user-images.githubusercontent.com/3084440/148574000-357e077a-6183-46c8-b893-ebac82468ae8.png">
npm i pulsar-client passes and the container gets deployed but stops running due to this error. 
<img width="600" alt="Screen Shot 2022-01-07 at 10 07 34 AM" src="https://user-images.githubusercontent.com/3084440/148574083-a65b3b83-84ed-4d88-ab00-84d7cb5c22a8.png">
Any ideas on why docker container can not access that file?

**Comment by Hoskins355** [comment]
@ zhaoyajun2009, Thanks I got it working.

**Comment by zhaoyajun2009** [comment]
fix it as follow:
https://github.com/apache/pulsar/pull/13999

**Comment by nkurihar** [comment]
Thanks for fixing the document 👍
