### ISSUE TITLE
Latest version is deprecated?

### ISSUE THREAD

**Issue by larshp** [apache/pulsar-client-node#199]
Hi,
It looks like the latest version is set to deprecated? What does this mean exactly, will you be releasing a new version, or targeting to deprecate all versions?

https://www.npmjs.com/package/pulsar-client,
![image](https://user-images.githubusercontent.com/5888506/156542060-bd7d22dd-98b6-4786-a58e-301051e81c02.png)

**Comment by nkurihar** [comment]
A few days ago, some versions (1.5.2, 1.5.1, 1.4.3, ...) were accidentally uploaded to the repositry.
They are not verified beforhand and so we deprecated them to avoid users downloading.

(Ideally they should be removed completely from the repository. 
However unfortunately, once uploaded it is not allowed to remove packages depended from at least one package...)

That's why the "latest" version is not 1.5.2 but 1.5.0 for now.
Moreover, the next version 1.6 is under voting, expected to be latest a few days later.

Sorry for confusing you.

**Comment by larshp** [comment]
thanks for the clarification

suggest keeping this issue open until 1.6 is released, but feel free to close 😅

**Comment by nkurihar** [comment]
Yes, let's keep this issue open until versions back to normal.

**Comment by nkurihar** [comment]
We have tagged 1.5.0 as "latest".
https://www.npmjs.com/package/pulsar-client

Now versions have backed to normal (though deprecated versions are still remaining in the registy).

Please use NON-deprecated versions, i.e., followings at this time:

<img width="748" alt="versions" src="https://user-images.githubusercontent.com/22067228/156712224-ce3ce57c-58be-4309-82b4-8423ce8df7ff.png">
