### ISSUE TITLE
How do i install libpulsar@2.10.2 through homebrew

### ISSUE THREAD

**Issue by Mporsi** [apache/pulsar-client-node#260]
Hi!
 
My team recently started using the pulsar node client. The team now has to install the c++ lib through brew.

We can only install 3.1.0 through brew, we are not in a pulsar 3.x instance 

As far as I can see 3.x.x. isn't yet released anywhere so why is that the latest stable on brew?

**Comment by veimox** [comment]
I am afraid there is a good fair amount of confusion here for Mac users.

It all started with https://github.com/Homebrew/homebrew-core/pull/114737 where the `libpulsar` is bumped to `3.0.0`. The reason is a monorepo split where they take out the `cpp` and `python` clients into their own repos (e.g. [ccp](https://github.com/apache/pulsar-client-cpp)) for technical reasons. Until that moment the clients where following the same versioning system as Pulsar it self (e.g. `2.10.0`) but for the new clients they broke this convention and now it has its own versioning scheme (thus the `3.X.X`). This how now nothing to do with the Pulsar version itself.

The error that you are seeing is (if you check the logs) the same as #254 and it has 2 solutions imo:
1. Wait for `1.8.0` where I understand from https://github.com/apache/pulsar-client-node/issues/254#issuecomment-1336116803 that it will be solved
2. Follow as suggested in https://github.com/apache/pulsar-client-node/issues/254#issuecomment-1342821737 and use the [instructions of 1.7.0 for Mac](https://github.com/apache/pulsar-client-node/tree/v1.7.0#install-on-mac). Note the different settings for both Intel and Apple Silicon chips.

**Comment by Mporsi** [comment]
Awesome @shibd !
