### ISSUE TITLE
Setup document is inaccurate

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar-client-node#306]
cc @shibd @RobertIndie @momo-jun 

https://pulsar.apache.org/docs/next/client-libraries-node-setup/

The first tip writes:

> Pulsar Node.js client library is based on the C++ client library.
> 
> * You must install the Pulsar C++ client library before installing a Node.js client. For more details, see [instructions](https://pulsar.apache.org/docs/next/client-libraries-cpp/).
> * If an incompatible version of the C++ client is installed, you may fail to build or run the Node.js library. For the compatibility between each version of the Node.js client and the C++ client, see [README](https://github.com/apache/pulsar-client-node/blob/master/README.md).

However, starting from 1.8.0, the README writes that:

> These instructions are only available for versions after 1.8.0. For versions previous to 1.8.0, you need to install the C++ client first. Please switch to the corresponding version branch of this repo to read the specific instructions.

I guess the setup instructions and notes should be updated?

**Comment by momo-jun** [comment]
@tisonkun Thanks for pointing out this inconsistency. 
IMO, it's better to make it single-sourced to avoid such unconscious inconsistencies; otherwise, the sync of updates can be easily missed.

@shibd @RobertIndie Can you pls advise?
1. Which statement is more accurate to use?
2. Which page plays the source role better regarding the installation? Pulsar doc page or README?

**Comment by shibd** [comment]
> I guess the setup instructions and notes should be updated?

Yes


> Which page plays the source role better regarding the installation? Pulsar doc page or README?

I think we can use the [README#Getting Started](https://github.com/apache/pulsar-client-node#getting-started) part
