### ISSUE TITLE
When will release 2.4？

### ISSUE THREAD

**Issue by MedusaLeee** [apache/pulsar-client-node#36]
When will release 2.4？

**Comment by nkurihar** [comment]
Hi, thank you for your comment!

Please let me confirm that what you meant "2.4 release":
* Do you wait for the release announcement of the node.js client?
* Do you want to use some features implemented in 2.4 C++ client?

Since our current status is considering the release procedure,
could you please wait about a month for the first release(publishing packages to npm registry and the announcement)?

**Comment by nkurihar** [comment]
https://www.npmjs.com/package/pulsar-client/v/1.0.0
Now 1.0.0 is released.
It's compatible with C++ Cliet 2.3.0 or later.
